import { createSupabaseModel } from "../db/supabase-model.js";

export const User = createSupabaseModel("users");
export const Department = createSupabaseModel("departments");
export const Subject = createSupabaseModel("subjects");
export const Document = createSupabaseModel("documents");
export const DocumentChunk = createSupabaseModel("document_chunks");
export const Quiz = createSupabaseModel("quizzes");
export const Question = createSupabaseModel("questions");
export const Attempt = createSupabaseModel("attempts");
export const TopicMastery = createSupabaseModel("topic_mastery");
export const Announcement = createSupabaseModel("announcements");
export const AuditLog = createSupabaseModel("audit_logs");
export const Escalation = createSupabaseModel("escalations");
export const RagInteractionLog = createSupabaseModel("rag_interaction_logs");
export const Module = createSupabaseModel("modules");
export const Resource = createSupabaseModel("resources");
export const Notification = createSupabaseModel("notifications");
export const Discussion = createSupabaseModel("discussions");
export const Feedback = createSupabaseModel("feedbacks");
export const ConceptNode = createSupabaseModel("concept_nodes");
export const ConceptEdge = createSupabaseModel("concept_edges");
export const Conversation = createSupabaseModel("conversations");
